import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./header";
import { LanguageProvider } from "./context/Language";
import AnimateWrapper from "./animasi";
import CompactNav from "./components/ui/CompactNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portofolio Nada Haifa",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LanguageProvider>
          {/* Global Compact Navigation (Appears on scroll with name from left, CV & social buttons) */}
          <CompactNav />

          <div className="relative">
            {/* FIRST SLIDE: STICKY HEADER (Stays pinned in viewport while user scrolls) */}
            <div className="sticky top-0 h-screen w-full z-0 overflow-hidden">
              <AnimateWrapper>
                <Header />
              </AnimateWrapper>
            </div>

            {/* SECOND SLIDE: CONTENT (Slides up from below and covers the header like a curtain) */}
            <div className="relative z-20">
              {children}
            </div>
          </div>
        </LanguageProvider>
      </body>
    </html>
  );
}
